#!/usr/bin/env bash

##
# This file is part of the JAT-Box project
#
# node: This script can be used on a slave machine to connect it to the server
# machine and allow the slave machine to run browser-dependent tests.
################################################################################

# get the directory in which this script is stored
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source ${DIR}/_common

# Param 1: A browser argument like "-browser browserName=chrome,maxInstances=3 -browser browserName=firefox,maxInstances=3"
BROWSER=$1
if [[ "$BROWSER" == "" ]]; then
    echo "Missing browser definition - eg \`node \"-browser browserName=chrome\"\`. Defaulting to Firefox and Chrome";
    BROWSER="-browser browserName=chrome -browser browserName=firefox";
fi

# Determine what system we are running in. We currently don't test for 32 vs 64 bit systems - we just assume Mac is 64
# bit, and Windows/Linux are 32. That's just a pragmatic decision - if there is a need we can add additional drivers
# and add sniffing for 32 vs 64 bit.
UNAME=$( uname -s )
if [[ "$UNAME" == "Darwin" ]]; then
    SYSTEM="mac64"
elif [[ "$UNAME" == "Linux" ]]; then
    SYSTEM="linux32"
else
    # For the time being we are simply assuming you're in Windows if one of the above cases doesn't apply.
    SYSTEM="win32"
fi

launch-selenium-node ${SYSTEM} "${BROWSER}"